--Pergunta: 2.2 Utilizando DB2
--Resposta: 

CREATE TABLE CLIENTE
(
ID_CLI INTEGER NOT NULL,
NOME VARCHAR(100),
EMAIL VARCHAR(100),
TELEFONE VARCHAR(20),
DATACADASTRO DATE,
TIPODOCUMENTO INTEGER,
NUMERODOCUMENTO VARCHAR(30),
PRIMARY KEY (ID_CLI)
);
CREATE INDEX IDX_CLI_ID_DOC ON CLIENTE (ID_CLI, NUMERODOCUMENTO); 


CREATE TABLE PEDIDO
(
ID_PEDIDO INTEGER NOT NULL,
TIPOPRODUTO INTEGER,
QTD INTEGER,
VALORUNITARIO FLOAT,
ID_CLI INTEGER,
PRIMARY KEY (ID_NOTA)
);
CREATE INDEX IDX_PEDIDO_ID_PED_NOTA ON PEDIDO (ID_PEDIDO, ID_NOTA);



CREATE TABLE NOTAFISCAL
(
ID_NOTA INTEGER NOT NULL,
DATAEMISSAO DATE,
VALORBRUNO FLOAT,
VALORIMPOSTOS FLOAT,
ID_PEDIDO INTEGER,
PRIMARY KEY (ID_PEDIDO)
);
CREATE INDEX IDX_PEDIDO_ID_PED_CLI ON PEDIDO (ID_PEDIDO, ID_CLI);



ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_CLI FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI);
ALTER TABLE NOTAFISCAL ADD CONSTRAINT FK_NOTA_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO);



--Pergunta: 2.3 Utilizando DB2
--Resposta: 
SELECT * FROM PEDIDOS 
ORDER BY QTD DESC



--Pergunta: 2.4 Utilizando DB2
--Resposta: 
SELECT NF.*
FROM NOTAFISCAL NF
INNER JOIN PEDIDOS PED ON (PED.ID_PEDIDO = NF.ID_PEDIDO)
INNER JOIN CLIENTE CLI ON (CLI.ID_CLI = PED.ID_CLI)
WHERE CLI.ID_CLI = 1


--Pergunta: 2.5 Utilizando DB2
--Resposta: Clientes que não tiverem pedidos não terão notas
SELECT *
FROM CLIENTES CLI
WHERE CLI.ID_CLI NOT IN (SELECT PED.ID_CLI
                         FROM PEDIDO PED)
